#!/usr/bin/env bash
# Generates shell/Menu/emoji.json from Unicode's published emoji-test.txt,
# fully-qualified entries only, in file order (Unicode group order, base
# emoji before their skin-tone variants). The output is vendored: run this
# once when bumping the Unicode version; the shell never generates at
# runtime. Menu.qml parses the file with Model.parseJsonc, which strips the
# provenance header comments this script writes.
#
# usage: dev/gen-emoji.sh [unicode-version]   (default 17.0.0)
set -euo pipefail

version="${1:-17.0.0}"
url="https://www.unicode.org/Public/${version}/emoji/emoji-test.txt"
repo_root=$(cd "$(dirname "$0")/.." && pwd)
out="$repo_root/shell/Menu/emoji.json"

src=$(curl -fsSL "$url")

# No early awk exit: closing the pipe mid-write would SIGPIPE printf, which
# pipefail turns into a script abort.
file_version=$(printf '%s\n' "$src" | awk -F': ' '/^# Version:/ { v = $2 } END { print v }')
if [ -z "$file_version" ]; then
  echo "gen-emoji: no '# Version:' header in $url" >&2
  exit 1
fi

# Data lines: `1F44D ; fully-qualified # 👍 E0.6 thumbs up`. The emoji char
# sits between the comment marker and the E<version> token, the name after.
printf '%s\n' "$src" | awk -v url="$url" -v ver="$file_version" '
function jsonEscape(s) {
    gsub(/\\/, "\\\\", s)
    gsub(/"/, "\\\"", s)
    return s
}
BEGIN {
    print "// Generated by dev/gen-emoji.sh, never edit by hand: regenerate instead."
    print "// Source: " url " (Emoji " ver ")"
    print "// License: Unicode License v3, https://www.unicode.org/license.txt"
    print "// Fully-qualified entries only, [{ch, name, group}] in file order."
    print "["
    n = 0
}
/^# group: / { group = substr($0, 10); next }
/; fully-qualified/ {
    rest = substr($0, index($0, "# ") + 2)
    sp = index(rest, " ")
    ch = substr(rest, 1, sp - 1)
    rest = substr(rest, sp + 1)
    name = substr(rest, index(rest, " ") + 1)
    if (n++) printf ",\n"
    printf "  {\"ch\": \"%s\", \"name\": \"%s\", \"group\": \"%s\"}", \
        jsonEscape(ch), jsonEscape(name), jsonEscape(group)
}
END { print ""; print "]" }
' > "$out"

count=$(grep -c '"ch"' "$out")
echo "wrote $out ($count entries, Emoji $file_version)"
