#!/usr/bin/env bash
# Generates shell/Menu/emoji.json from Unicode's published emoji-test.txt,
# fully-qualified entries only, in file order (Unicode group order, base
# emoji before their skin-tone variants). The output is vendored: run this
# once when bumping the Unicode version; the shell never generates at
# runtime. Menu.qml parses the file with Model.parseHeaderedJson, which
# skips the provenance header comments this script writes and hands the
# rest to the native JSON.parse.
#
# Each entry also carries CLDR's English search keywords ("kw", pipe
# separated), which is the same annotation data macOS, iOS and Android type
# their emoji pickers against: emoji-test.txt alone knows 😂 as "face with
# tears of joy" and nothing else, so "lol", "cry" and "haha" find it here
# only because CLDR says so. Two files, since CLDR splits them: the base
# annotations, and the derived ones covering skin-tone and other sequences.
# Keywords already findable in the name are dropped at generation time
# (CLDR repeats the name's own words in most entries), so "kw" only ever
# holds terms the name search would miss, and is omitted entirely when it
# would be empty.
#
# Needs jq (the CLDR data is JSON, emoji-test.txt is not).
#
# usage: dev/gen-emoji.sh [unicode-version]   (default 17.0.0)
set -euo pipefail

version="${1:-17.0.0}"
url="https://www.unicode.org/Public/${version}/emoji/emoji-test.txt"
cldr_base="https://raw.githubusercontent.com/unicode-org/cldr-json/main/cldr-json"
ann_url="$cldr_base/cldr-annotations-full/annotations/en/annotations.json"
annd_url="$cldr_base/cldr-annotations-derived-full/annotationsDerived/en/annotations.json"
repo_root=$(cd "$(dirname "$0")/.." && pwd)
out="$repo_root/shell/Menu/emoji.json"

src=$(curl -fsSL "$url")

# `<char> TAB kw|kw|kw`, base annotations then derived. Keys are disjoint
# between the two files (derived only carries sequences the base file has no
# entry for), so the awk lookup below keeps whichever it sees first.
kwfile=$(mktemp)
trap 'rm -f "$kwfile"' EXIT
{
  curl -fsSL "$ann_url" |
    jq -r '.annotations.annotations | to_entries[] | [.key, (.value.default // [] | join("|"))] | @tsv'
  curl -fsSL "$annd_url" |
    jq -r '.annotationsDerived.annotations | to_entries[] | [.key, (.value.default // [] | join("|"))] | @tsv'
} > "$kwfile"

# No early awk exit: closing the pipe mid-write would SIGPIPE printf, which
# pipefail turns into a script abort.
file_version=$(printf '%s\n' "$src" | awk -F': ' '/^# Version:/ { v = $2 } END { print v }')
if [ -z "$file_version" ]; then
  echo "gen-emoji: no '# Version:' header in $url" >&2
  exit 1
fi

# Data lines: `1F44D ; fully-qualified # 👍 E0.6 thumbs up`. The emoji char
# sits between the comment marker and the E<version> token, the name after.
printf '%s\n' "$src" | awk -v url="$url" -v ver="$file_version" -v kwfile="$kwfile" '
function jsonEscape(s) {
    gsub(/\\/, "\\\\", s)
    gsub(/"/, "\\\"", s)
    return s
}
# CLDR keywords for `ch` that the name does not already contain, lowercased,
# pipe separated. The name comparison is what keeps the file from doubling in
# size for nothing: CLDR lists "grinning face" and "face" against 😀, both of
# which the name search already finds.
function keywords(ch, name,    parts, n, i, term, out) {
    if (!(ch in KW)) return ""
    n = split(KW[ch], parts, "|")
    out = ""
    for (i = 1; i <= n; i++) {
        term = tolower(parts[i])
        if (term == "" || index(tolower(name), term) > 0) continue
        out = (out == "") ? term : out "|" term
    }
    return out
}
BEGIN {
    while ((getline line < kwfile) > 0) {
        tab = index(line, "\t")
        if (tab == 0) continue
        ch = substr(line, 1, tab - 1)
        if (!(ch in KW)) KW[ch] = substr(line, tab + 1)
    }
    close(kwfile)
    print "// Generated by dev/gen-emoji.sh, never edit by hand: regenerate instead."
    print "// Source: " url " (Emoji " ver ")"
    print "// Keywords: CLDR en annotations (base + derived), terms the name lacks."
    print "// License: Unicode License v3, https://www.unicode.org/license.txt"
    print "// Fully-qualified entries only, [{ch, name, group, kw?}] in file order."
    print "["
    n = 0
}
/^# group: / { group = substr($0, 10); next }
/; fully-qualified/ {
    rest = substr($0, index($0, "# ") + 2)
    sp = index(rest, " ")
    ch = substr(rest, 1, sp - 1)
    rest = substr(rest, sp + 1)
    name = substr(rest, index(rest, " ") + 1)
    kw = keywords(ch, name)
    if (n++) printf ",\n"
    printf "  {\"ch\": \"%s\", \"name\": \"%s\", \"group\": \"%s\"", \
        jsonEscape(ch), jsonEscape(name), jsonEscape(group)
    if (kw != "") printf ", \"kw\": \"%s\"", jsonEscape(kw)
    printf "}"
}
END { print ""; print "]" }
' > "$out"

count=$(grep -c '"ch"' "$out")
kwcount=$(grep -c '"kw"' "$out")
echo "wrote $out ($count entries, $kwcount with keywords, Emoji $file_version)"
