.pragma library

// Hand-mapped Nerd Font codepoints for the `nerd` icon set (theme.icons),
// the same Material Design Icons range shell/Menu/providers.js already
// draws bar/menu glyphs from (verified against nerd-fonts' own
// glyphnames.json, the source that patches JetBrainsMono Nerd Font). Only
// the names this milestone's surfaces need; M42+ tasks append more.
//
// "plug-zap" has no MDI glyph for a charging/live plug (checked every
// "plug"/"power_plug"/"ev_plug_*" entry in glyphnames.json): mapped to
// circle-help rather than guessing a wrong pairing.
var ICONS = {
    "wifi": "\u{F05A9}",
    "wifi-off": "\u{F05AA}",
    "bluetooth": "\u{F00AF}",
    "bluetooth-off": "\u{F00B2}",
    "volume": "\u{F0580}",
    "volume-1": "\u{F057F}",
    "volume-2": "\u{F057E}",
    "volume-x": "\u{F075F}",
    "mic": "\u{F036C}",
    "mic-off": "\u{F036D}",
    "battery": "\u{F0079}",
    "battery-charging": "\u{F0085}",
    "battery-low": "\u{F007B}",
    "battery-warning": "\u{F0083}",
    "sun": "\u{F0599}",
    "moon": "\u{F0594}",
    "bell": "\u{F009A}",
    "bell-off": "\u{F009B}",
    "clock": "\u{F0150}",
    "calendar": "\u{F00EE}",
    "search": "\u{F0349}",
    "command": "\u{F0633}",
    "x": "\u{F0156}",
    "check": "\u{F012C}",
    "lock": "\u{F033E}",
    "lock-open": "\u{F033F}",
    "refresh-cw": "\u{F0453}",
    "settings": "\u{F0493}",
    "power": "\u{F0425}",
    "monitor": "\u{F0379}",
    "cpu": "\u{F0EE0}",
    "memory-stick": "\u{F035B}",
    "hard-drive": "\u{F02CA}",
    "thermometer": "\u{F050F}",
    "activity": "\u{F0430}",
    "download": "\u{F01DA}",
    "upload": "\u{F0552}",
    "arrow-up": "\u{F005D}",
    "arrow-down": "\u{F0045}",
    "arrow-left": "\u{F004D}",
    "arrow-right": "\u{F0054}",
    "chevron-up": "\u{F0143}",
    "chevron-down": "\u{F0140}",
    "chevron-left": "\u{F0141}",
    "chevron-right": "\u{F0142}",
    "circle-help": "\u{F02D7}",
    "circle-alert": "\u{F0028}",
    "triangle-alert": "\u{F0026}",
    "info": "\u{F02FC}",
    "play": "\u{F040A}",
    "pause": "\u{F03E4}",
    "skip-back": "\u{F04AE}",
    "skip-forward": "\u{F04AD}",
    "shuffle": "\u{F049D}",
    "repeat": "\u{F0456}",
    "image": "\u{F02E9}",
    "camera": "\u{F0100}",
    "video": "\u{F0567}",
    "clipboard": "\u{F0147}",
    "keyboard": "\u{F030C}",
    "terminal": "\u{F018D}",
    "package": "\u{F03D3}",
    "cloud": "\u{F015F}",
    "cloud-rain": "\u{F0597}",
    "cloud-sun": "\u{F0595}",
    "zap": "\u{F0241}",
    "plus": "\u{F0415}",
    "minus": "\u{F0374}",
    "trash": "\u{F0A79}",
    "pencil": "\u{F03EB}",
    "external-link": "\u{F03CC}",
    "ellipsis": "\u{F01D8}",
    "menu": "\u{F035C}",
    "grid-2x2": "\u{F0570}",
    "list": "\u{F0279}",
    "star": "\u{F04CE}",
    "heart": "\u{F02D1}",
    "globe": "\u{F01E7}",
    "map-pin": "\u{F034E}",
    "user": "\u{F0004}",
    "users": "\u{F0849}",
    "home": "\u{F02DC}",
    "folder": "\u{F024B}",
    "file": "\u{F0214}",
    "save": "\u{F0193}",
    "copy": "\u{F018F}",
    "share-2": "\u{F0497}",
    "send": "\u{F048A}",
    "mail": "\u{F01EE}",
    "message-square": "\u{F0369}",
    "phone": "\u{F03F2}",
    "headphones": "\u{F02CB}",
    "gamepad-2": "\u{F0297}",
    "printer": "\u{F042A}",
    "usb": "\u{F0553}",
    "plug": "\u{F06A5}",
    "plug-zap": "\u{F02D7}"
};

var FAMILY = "";
