//! The emoji route: name and keyword search over the vendored dataset
//! (`emoji.json`, generated by `dev/gen-emoji.sh`).

use serde::Deserialize;

use super::apps::now_ms;
use crate::frecency::{self, Record};
use crate::jsstr;
use crate::node::{Kind, Node};

/// One dataset entry. `kw` is CLDR's lowercase, pipe separated annotations;
/// it is optional per entry (CLDR has nothing extra for some, and the
/// generator drops keywords the name already carries).
#[derive(Clone, Debug, Default, PartialEq, Deserialize)]
pub struct EmojiEntry {
    pub ch: String,
    pub name: String,
    #[serde(default)]
    pub group: String,
    #[serde(default)]
    pub kw: Option<String>,
}

/// `":e "` root trigger (the DMS muscle-memory prefix): the emoji query after
/// it, "" for `":e "` alone (browse mode), or `None` when `text` is not the
/// trigger at all. The space is part of the trigger: it swaps the whole view
/// for the emoji grid, and a bare `":e"` also starts `":ex..."` and every
/// other word, which swapped to the grid and straight back on the next
/// letter.
pub fn emoji_trigger_query(text: &str) -> Option<&str> {
    text.strip_prefix(":e ")
}

/// The ledger id for an emoji, the row id the launcher records on
/// activation, so `state.json` stays readable ("emoji.<char>") and both sides
/// spell it once.
pub fn emoji_usage_id(entry: &EmojiEntry) -> String {
    format!("emoji.{}", entry.ch)
}

struct Indexed {
    entry: EmojiEntry,
    lc_name: String,
    /// The keywords wrapped in the pipe the generator joins them with, so a
    /// whole-keyword hit is one `contains("|q|")` rather than a split per
    /// entry per keystroke. "" for an entry CLDR has nothing extra for, which
    /// matches no query.
    kw_index: String,
    usage_id: String,
}

/// The dataset with every per-keystroke derivation computed once: each
/// keystroke rescans all 3944 names, and lowercasing them again each time is
/// the one part of that scan worth not repeating. Build it once per dataset
/// load and keep it for the life of the shell.
pub struct EmojiIndex {
    entries: Vec<Indexed>,
}

impl EmojiIndex {
    pub fn new(list: Vec<EmojiEntry>) -> EmojiIndex {
        let entries = list
            .into_iter()
            .map(|entry| Indexed {
                lc_name: entry.name.to_lowercase(),
                kw_index: match entry.kw.as_deref() {
                    Some(kw) if !kw.is_empty() => format!("|{kw}|"),
                    _ => String::new(),
                },
                usage_id: emoji_usage_id(&entry),
                entry,
            })
            .collect();
        EmojiIndex { entries }
    }

    pub fn len(&self) -> usize {
        self.entries.len()
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    pub fn entries(&self) -> impl Iterator<Item = &EmojiEntry> {
        self.entries.iter().map(|i| &i.entry)
    }

    /// Name and keyword search. Six tiers: name exact > name starts-with >
    /// name word-start > keyword exact > name contains > keyword word-start,
    /// ties broken by file order, which puts base emoji ahead of their
    /// skin-tone variants for free. An empty query browses the whole set, so
    /// the summoned route is never an empty surface and never a truncated one
    /// (all 3944 are reachable; a grid only instantiates the cells it can
    /// see).
    ///
    /// The keyword tiers are CLDR's own annotations, the data macOS and iOS
    /// type their pickers against: Unicode's name for the crying face is
    /// "loudly crying face" and nothing else, so "sob" reaches it only through
    /// `kw`. They sit below every name tier because a name match is the one
    /// the user can see on the row, and above `name contains` because an entry
    /// whose whole keyword is the query beats one that merely has the letters
    /// inside a longer word.
    ///
    /// `uses` (the emoji ledger) and `now` reorder WITHIN each tier, never
    /// across: what gets used most leads the browse grid and leads among
    /// equally-good matches, and a better match still wins outright.
    pub fn search(&self, query: &str, uses: &[Record], now: Option<f64>) -> Vec<&EmojiEntry> {
        let q = jsstr::trim(query).to_lowercase();
        if q.is_empty() {
            return rank(self.entries.iter().collect(), uses, now);
        }
        // Buckets rather than a comparator sort: there are exactly six tiers
        // and the scan already visits the list in file order, so pushing into
        // a bucket and concatenating them highest-first yields the same order
        // (tier descending, file order within a tier) in one linear pass. A
        // one-letter query matches most of the dataset.
        let mut buckets: [Vec<&Indexed>; 6] = Default::default();
        let word_start = format!(" {q}");
        let kw_whole = format!("|{q}|");
        let kw_start = format!("|{q}");
        for item in &self.entries {
            let name = item.lc_name.as_str();
            let kw = item.kw_index.as_str();
            let tier = if name == q {
                0
            } else if name.starts_with(&q) {
                1
            } else if name.contains(&word_start) {
                2
            } else if kw.contains(&kw_whole) {
                3
            } else if name.contains(&q) {
                4
            } else if kw.contains(&kw_start) || kw.contains(&word_start) {
                5
            } else {
                continue;
            };
            buckets[tier].push(item);
        }
        buckets.into_iter().flat_map(|b| rank(b, uses, now)).collect()
    }

    /// Emoji rows are plain "action" nodes: Enter runs `wl-copy` through the
    /// existing activation path and closes, and the clipboard service captures
    /// the copy like any other. The char rides the icon slot, the uppercase
    /// name is the label. Single quotes are required around the char: keycap
    /// sequences start with ASCII `#`/`*`/digits (comment and glob hazards
    /// unquoted), and no emoji contains an ASCII apostrophe.
    ///
    /// `paste` is `clipboard.paste`, threaded in so this stays pure: it marks
    /// the row for the paste hook, which synthesizes the chord into whatever
    /// window focus returns to, on top of the copy that already ran. The old
    /// path typed the char itself with `wtype <char>`, which only lands where
    /// the focused client accepts a remapped keysym off a virtual keyboard; a
    /// paste works wherever the user's own paste chord already works.
    pub fn rows(&self, query: &str, paste: bool, uses: &[Record], now: Option<f64>) -> Vec<Node> {
        self.search(query, uses, now)
            .into_iter()
            .map(|e| Node {
                icon: e.ch.clone(),
                verb: Some(if paste { "Paste" } else { "Copy" }.to_string()),
                action: Some(format!("wl-copy -- '{}'", e.ch)),
                paste_after: paste,
                ..Node::new(emoji_usage_id(e), e.name.to_uppercase(), Kind::Action)
            })
            .collect()
    }
}

/// Most-used first inside one tier, file order for everything the ledger has
/// never seen. An absent or empty ledger costs nothing and changes nothing: a
/// fresh profile browses the grid in Unicode's own order. `pull_recorded`
/// rather than `order`: a broad query's tier can hold thousands of entries,
/// and only the ones the ledger actually scores ever move.
fn rank<'a>(entries: Vec<&'a Indexed>, uses: &[Record], now: Option<f64>) -> Vec<&'a EmojiEntry> {
    if uses.is_empty() {
        return entries.into_iter().map(|i| &i.entry).collect();
    }
    // `nowMs || Date.now()`: a zero clock reads as absent.
    let now = now.filter(|n| *n != 0.0).unwrap_or_else(now_ms);
    frecency::pull_recorded(entries, uses, now, |i| i.usage_id.as_str())
        .into_iter()
        .map(|i| &i.entry)
        .collect()
}
