[package]
name = "fs-menu"
version = "0.1.1"
edition = "2024"
publish = false

[dependencies]
fs-devices = { path = "../fs-devices" }
fs-js = { path = "../fs-js" }
chrono = "0.4"
indexmap = { version = "2", features = ["serde"] }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }

[dev-dependencies]
percent-encoding = "2"
