#!/usr/bin/env bash
# Generates shell/Theme/icons/lucide.js from the pinned Lucide release's
# lucide.css (name-to-codepoint map: `.icon-NAME::before { content:
# "\eXXX"; }`, where the escape's hex digits ARE the codepoint, "e" included,
# not a fixed "\e" prefix followed by three digits). The output is
# vendored: run this once when bumping the Lucide version pinned in
# nix/lucide-font.nix; the shell never generates at runtime.
#
# usage: tools/gen-lucide-icons.sh [version]   (default 1.34.0)
set -euo pipefail

version="${1:-1.34.0}"
url="https://github.com/lucide-icons/lucide/releases/download/${version}/lucide-font-${version}.zip"
repo_root=$(cd "$(dirname "$0")/.." && pwd)
out="$repo_root/shell/Theme/icons/lucide.js"

workdir=$(mktemp -d)
trap 'rm -rf "$workdir"' EXIT

curl -fsSL -o "$workdir/lucide-font.zip" "$url"
unzip -q "$workdir/lucide-font.zip" -d "$workdir"

css="$workdir/lucide-font/lucide.css"
if [ ! -f "$css" ]; then
  echo "gen-lucide-icons: no lucide.css in the unpacked release at $css" >&2
  exit 1
fi

# Codepoints are re-emitted as JS ES6 code point escapes (\u{XXX}) rather
# than the raw UTF-8 character, matching shell/Menu/providers.js's own icon
# table: a generated table never carries a raw codepoint, so it never falls
# under CLAUDE.md's glyph-corruption-on-rewrite hazard in the first place.
# Plain index()/substr(), no gawk-only match() array capture, the same
# portability dev/gen-emoji.sh's awk already relies on.
awk -v url="$url" '
function jsonEscape(s) {
    gsub(/\\/, "\\\\", s)
    gsub(/"/, "\\\"", s)
    return s
}
BEGIN {
    print "// Generated by tools/gen-lucide-icons.sh, never edit by hand: regenerate instead."
    print "// Source: " url
    print "// License: ISC, https://github.com/lucide-icons/lucide/blob/main/LICENSE"
    print ".pragma library"
    print ""
    print "var ICONS = {"
    n = 0
}
index($0, ".icon-") == 1 {
    marker = "::before { content: \"\\"
    mi = index($0, marker)
    if (mi == 0) next
    name = substr($0, 7, mi - 7)
    rest = substr($0, mi + length(marker))
    qi = index(rest, "\"")
    if (qi == 0) next
    code = substr(rest, 1, qi - 1)
    if (n++) printf ",\n"
    printf "    \"%s\": \"\\u{%s}\"", jsonEscape(name), toupper(code)
}
END {
    print ""
    print "};"
    print ""
    print "var FAMILY = \"lucide\";"
}
' "$css" > "$out"

count=$(grep -c '": "\\u{' "$out")
if [ "$count" -lt 1500 ]; then
  echo "gen-lucide-icons: only $count entries parsed from $css, expected at least 1500" >&2
  exit 1
fi

echo "wrote $out ($count entries, Lucide $version)"
