.pragma library

// Provider functions populate a "provider" kind node's children at
// tree-build time (Model.buildTree() infers "provider" from an entry's
// `provider` key — see default-menu.jsonc's "apps" node). Providers return
// ready-made Node fragments (Model's Node shape: id/label/icon/title/
// aliases/kind/childIds) rather than JSONC entries, because they bypass
// buildTree()'s action/target/provider kind inference entirely — an app has
// no `action` string, it has a DesktopEntry to call execute() on, which
// respects .desktop field codes/Exec quoting that re-running it through
// `sh -c` would mangle.

// `entries` = DesktopEntries.applications.values (Quickshell's built-in
// desktop-entry index, already excludes Hidden/NoDisplay). Each app node
// keeps a reference to its DesktopEntry (`_entry`) so Menu.qml's activation
// can call `_entry.execute()` directly instead of spawning a shell command.
function appsProvider(entries) {
    return (entries || []).map(function (entry) {
        return {
            id: "apps." + entry.id,
            parentId: null,
            label: entry.name,
            icon: entry.icon || "",
            title: entry.genericName || "",
            aliases: [],
            kind: "app",
            childIds: [],
            _entry: entry
        };
    });
}

// Merges every "provider" node's produced children into `tree` (a
// Model.buildTree() result): for each provider node, looks up its
// `provider` name in `providerFns` (name -> fn(): [Node]), parents the
// returned nodes under it, and registers them in `tree.nodes`. Mutates and
// returns `tree`.
function applyProviders(tree, providerFns) {
    Object.keys(tree.nodes).forEach(function (id) {
        var node = tree.nodes[id];
        if (node.kind !== "provider") return;
        var fn = providerFns[node.provider];
        if (!fn) return;
        fn().forEach(function (child) {
            child.parentId = node.id;
            tree.nodes[child.id] = child;
            node.childIds.push(child.id);
        });
    });
    return tree;
}

// Clipboard history rows, newest first (ClipboardService.items' own order).
// Unlike appsProvider these are plain "action" nodes — Menu.qml's existing
// `_activateRow`/`_runAction` spawn-command path already re-copies the entry
// via `qs ipc call clipboard copy <id>` with zero Menu.qml changes, so no
// bespoke node kind (and no `_entry`-style back-reference) is needed here.
//
// `selfPath` is the running shell's own config root (`Quickshell.shellDir`,
// e.g. `<store-path>/share/formalshell`) — without `--any-display -p
// <selfPath>` on the call, `qs ipc`'s instance lookup falls back to the
// default XDG quickshell config dir (command.cpp's locateConfigFile()/
// selectInstance()), which formalshell doesn't register under, so the copy
// would silently hit "No running instances" instead of this shell. Every
// other documented IPC call (README) passes the same two flags for the same
// reason.
function clipboardProvider(items, selfPath) {
    return (items || []).map(function (entry) {
        return {
            id: "clipboard." + entry.id,
            parentId: null,
            label: previewLabel(entry.text),
            icon: "",
            title: "",
            aliases: [],
            kind: "action",
            action: "qs ipc --any-display -p " + selfPath + " call clipboard copy " + entry.id,
            childIds: []
        };
    });
}

// First non-blank line only, capped at maxLen chars — clipboard captures can
// be multi-line/arbitrarily long, and MenuRow's label is a single Text with
// no wrapping, so anything longer needs pre-truncating here rather than
// spilling into the ledger row below it.
function previewLabel(text, maxLen) {
    maxLen = maxLen || 60;
    var lines = text.split("\n");
    var firstLine = "";
    for (var i = 0; i < lines.length; i++) {
        var trimmed = lines[i].trim();
        if (trimmed !== "") { firstLine = trimmed; break; }
    }
    if (firstLine === "") firstLine = text.trim();
    var truncated = firstLine.length > maxLen;
    var out = truncated ? firstLine.slice(0, maxLen) : firstLine;
    return (truncated || lines.length > 1) ? out + "…" : out;
}

var EMOJI_MAX_RESULTS = 40;

// ":e" root trigger (M12 Task 6, the DMS muscle-memory prefix): returns the
// emoji query after it, "" for the bare ":e" (browse mode), or null when
// `text` is not the trigger at all.
function emojiTriggerQuery(text) {
    var t = String(text || "");
    if (t === ":e") return "";
    if (t.indexOf(":e ") === 0) return t.slice(3);
    return null;
}

// Name search over the vendored emoji dataset (emoji.json, generated by
// dev/gen-emoji.sh, parsed by Menu.qml): exact > starts-with > word-start >
// contains, ties broken by file order, which puts base emoji ahead of their
// skin-tone variants for free. Empty query browses the head of the list so
// the summoned route is never an empty surface.
function emojiSearch(list, query) {
    list = list || [];
    var q = String(query || "").trim().toLowerCase();
    if (!q) return list.slice(0, EMOJI_MAX_RESULTS);
    var results = [];
    for (var i = 0; i < list.length; i++) {
        var name = String(list[i].name).toLowerCase();
        var tier;
        if (name === q) tier = 4;
        else if (name.indexOf(q) === 0) tier = 3;
        else if (name.indexOf(" " + q) >= 0) tier = 2;
        else if (name.indexOf(q) >= 0) tier = 1;
        else continue;
        results.push({ entry: list[i], tier: tier, index: i });
    }
    results.sort(function (a, b) {
        if (b.tier !== a.tier) return b.tier - a.tier;
        return a.index - b.index;
    });
    return results.slice(0, EMOJI_MAX_RESULTS).map(function (r) { return r.entry; });
}

// Emoji rows are plain "action" nodes (clipboardProvider's own trick): Enter
// runs `wl-copy` through the existing activation path and closes, and the
// clipboard service captures the copy like any other. The char rides the
// icon slot, the uppercase name is the label. Single quotes are required
// around the char: keycap sequences start with ASCII `#`/`*`/digits (comment
// and glob hazards unquoted), and no emoji contains an ASCII apostrophe.
function emojiRows(list, query) {
    return emojiSearch(list, query).map(function (e) {
        return {
            id: "emoji." + e.ch,
            parentId: null,
            label: e.name.toUpperCase(),
            icon: e.ch,
            title: "",
            aliases: [],
            kind: "action",
            action: "wl-copy -- '" + e.ch + "'",
            childIds: []
        };
    });
}

var NIX_MAX_RESULTS = 30;

// ":nix" root trigger (M12 Task 7): returns the package query after it, ""
// for the bare ":nix", or null when `text` is not the trigger at all. Same
// contract as emojiTriggerQuery above.
function nixTriggerQuery(text) {
    var t = String(text || "");
    if (t === ":nix") return "";
    if (t.indexOf(":nix ") === 0) return t.slice(5);
    return null;
}

// `nix search nixpkgs <q> --json` stdout -> [{attr, version, description}].
// Keys arrive as `legacyPackages.<system>.<attrpath>`; the first two dotted
// components are the flake/system prefix `nix run nixpkgs#<attr>` must not
// see, the remainder (itself possibly dotted: python312Packages.requests)
// is the attr. Object key order survives JSON.parse for string keys, so
// nix's own output order is kept. Unparsable stdout returns [] — the same
// honest nothing an empty result set gets.
function parseNixSearch(text) {
    var obj;
    try {
        obj = JSON.parse(text);
    } catch (e) {
        return [];
    }
    if (obj === null || typeof obj !== "object") return [];
    var out = [];
    Object.keys(obj).forEach(function (key) {
        var attr = key.split(".").slice(2).join(".");
        if (attr === "") return;
        var entry = obj[key] || {};
        out.push({
            attr: attr,
            version: String(entry.version || ""),
            description: String(entry.description || "")
        });
    });
    return out;
}

// Search-result rows are plain "action" nodes: Enter spawns the package in
// a throwaway terminal through the existing activation path and closes.
// `read` holds the window open after the program exits so its output is
// actually readable. The attr is interpolated into a single-quoted sh
// string, so anything outside the safe attr charset is skipped outright
// rather than escaped — nixpkgs attrs are [A-Za-z0-9._+-] in practice.
function nixRows(results) {
    var out = [];
    (results || []).forEach(function (r) {
        if (out.length >= NIX_MAX_RESULTS) return;
        if (!/^[A-Za-z0-9._+-]+$/.test(r.attr)) return;
        out.push({
            id: "nix." + r.attr,
            parentId: null,
            label: r.version !== "" ? r.attr + " " + r.version : r.attr,
            icon: "",
            title: "",
            desc: r.description !== "" ? previewLabel(r.description) : "",
            aliases: [],
            kind: "action",
            action: "ghostty -e sh -c 'nix run nixpkgs#" + r.attr + "; read'",
            childIds: []
        });
    });
    return out;
}

// The honest single dim row for a host with no `nix` on PATH (kind "note":
// not activatable, MenuRow renders the label via foregroundDim).
function nixUnavailableRow() {
    return {
        id: "nix.unavailable",
        parentId: null,
        label: "NO NIX",
        icon: "",
        title: "",
        aliases: [],
        kind: "note",
        dim: true,
        childIds: []
    };
}

// Expands Config's `menu.customPowerButtons` (the spec's "first-class, not
// a workaround" case — e.g. an owner's Windows-reboot bootloader shortcut)
// into JSONC-shaped entry fragments keyed by dotted id, meant to be merged
// into the default tree object before Model.buildTree() runs:
// `system.custom.<i>` auto-nests under the already-declared `system` node
// exactly like any other dotted id.
function customPowerButtonEntries(buttons) {
    var out = {};
    (buttons || []).forEach(function (btn, i) {
        out["system.custom." + i] = {
            label: btn.label,
            icon: btn.icon || "",
            action: btn.command,
            confirm: btn.confirm === true
        };
    });
    return out;
}

// Root "wallpaper" node (M13 Task 5), merged into the default tree object
// before Model.buildTree() exactly like customPowerButtonEntries above —
// it can't live in default-menu.jsonc because the action needs the running
// shell's own path (clipboardProvider's selfPath rationale). Activation
// spawns the self-targeting `qs ipc call picker summon` rather than opening
// the picker in-process: the spawned call lands after the menu surface has
// already closed, so the picker never fights the menu's keyboard-exclusive
// focus.
function wallpaperEntry(selfPath) {
    return {
        "wallpaper": {
            label: "Wallpaper",
            icon: "\u{F0E09}", // nf-md-wallpaper
            action: "qs ipc --any-display -p " + selfPath + " call picker summon"
        }
    };
}
